export enum GamificationActionTypes {
   ADD_ACTIVITY = "gamification/activity/add",
   DELETE_ACTIVITY = "gamification/activity/delete",
   SET_ACTIVITIES = "gamification/activity/set",
   REGISTER = "gamification/authentication/register",
   LOGIN = "gamification/authentication/login",
   SET_CREATION_DATE = "gamification/authentication/creation_date",
   SET_USER_ID = "gamification/authentication/user_id",
   SET_EMAIL = "gamification/authentication/set_email",
   SET_STAY_LOGGED_IN = "gamification/authentication/set_logged_in",
   SET_ACTIVE_ACTIVITY = "gamification/activities/set_active_activity",
   UPDATE_CELL = "gamification/cells/update",
   DELETE_CELL = "gamification/cells/delte",
   SET_DAYS_IN_MONTH = "gamification/calendar/date",
   SET_CURRENTLY_SELECTED_MONTH = "gamification/calendar/selected_month",
}